### ISSUE TITLE
Update release

### ISSUE THREAD

**Issue by zacksiri** [danielberkompas/elasticsearch-elixir#103]
I saw there are a few branches that got merged. 1.0.1 is currently not matching with what's in the `master` branch. ANy chance we can get a release update?

**Comment by vanvoljg** [comment]
The recent merge of Telemetry events would also be wonderful to see in a release. Currently, I'm locked to the most recent commit on `master` (in a fork of mine), but it would be great to be able to go with a Hex release.

**Comment by danielberkompas** [comment]
I've released v1.1.0 with the latest merged changes, see the [changelog](https://github.com/danielberkompas/elasticsearch-elixir/blob/master/CHANGELOG.md#v110-2023-09-15).

**Comment by danielberkompas** [comment]
cc @Stratus3D

**Comment by Stratus3D** [comment]
Thanks Daniel!
