### ISSUE TITLE
Example of working app

### ISSUE THREAD

**Issue by hipertracker** [danielberkompas/elasticsearch-elixir#56]
Could you add a full working Phoenix example with small Ecto model having some relations? I can't figure out how to use this library.

**Comment by sc4224** [comment]
I noticed in the configuration that it refers to a file located in "priv/elasticsearch/posts.json" How do we set that file up? Give us an example please.

**Comment by danielberkompas** [comment]
@sc4224 You can see an example [here](https://github.com/infinitered/elasticsearch-elixir/blob/master/test/support/settings/posts.json). It's the same settings that you post to Elasticsearch when you [create an index](https://www.elastic.co/guide/en/elasticsearch/reference/6.6/indices-create-index.html).

**Comment by gabriel137** [comment]
I nerd to
