### ISSUE TITLE
Problem building

### ISSUE THREAD

**Issue by jhonathas** [danielberkompas/elasticsearch-elixir#69]
Hi everyone, I'm trying this problem here:

![image](https://user-images.githubusercontent.com/28179/56383579-83a22e00-61f0-11e9-98cd-fdce4a23ff01.png)

I've already tried using Elasticsearch with Jason and Poison and the error continues. You know what may be happening?

I completely cleared the Elasticsearch thinking there might be some duplicity, but it did not work.

The command I use is this:
mix elasticsearch.build dev-profiles --cluster V2V.ElasticsearchCluster

**Comment by danielberkompas** [comment]
@jhonathas According to the Elasticsearch docs, this should only happen when you write the same document to an index twice, while specifying the `?version` parameter. The `?version` querystring parameter tells Elasticsearch to reject writes if the `_version` field in the document is different than the one in the query string.

https://www.elastic.co/guide/en/elasticsearch/guide/current/optimistic-concurrency-control.html

Some questions that will help nail this down:

- What version of Elasticsearch are you using?
- Are you including `_version` in your documents? (In the Elasticsearch.Document implementations)

**Comment by jhonathas** [comment]
Hi, 
My elastic search version, is: 6.5.2.

Follow print from my document.

The example of the error that I had presented was of the ProfileDocument, but since it is giving error in others also, follows print of the document. I do not use version inside.

![image](https://user-images.githubusercontent.com/28179/56428794-0ed5ff00-6297-11e9-9771-05e0c350407b.png)

Taking advantage, an error that gives several times and it may be that one error has connection with the other is this error here:

![image](https://user-images.githubusercontent.com/28179/56428908-6d9b7880-6297-11e9-8991-54eb8d70de1f.png)

Thank you very much for the help

**Comment by jhonathas** [comment]
The error continues. From what I saw the error happens here - 

https://github.com/danielberkompas/elasticsearch-elixir/blob/master/lib/elasticsearch/indexing/bulk.ex#L111

And when it goes from there, it gives error here - 

https://github.com/danielberkompas/elasticsearch-elixir/blob/master/lib/elasticsearch/indexing/index.ex#L147

These are the 2 code locations that time out.

I tried to do this in the store:

```
   @impl true
   def transaction (fun) do
     {: ok, result} = Repo.transaction(fun, pool_timeout: :infinity, timeout: :infinity)
     result
   end
```
But it did not resolve. 

Any idea?

**Comment by danielberkompas** [comment]
@jhonathas I'm sorry you're still experiencing this issue. Unfortunately, I don't have a clear idea what might be causing it. :-( Happy for anyone to help with this who can.
