### ISSUE TITLE
Maximum amount of index saved

### ISSUE THREAD

**Issue by jhonathas** [danielberkompas/elasticsearch-elixir#84]
Hello people.

Is it possible for me to set the number of indexes that will be saved when I build? I have several versions and would like to exclude them automatically when I run the build.

**Comment by danielberkompas** [comment]
For anyone in the future who has this problem, you can specify the indexes to build by name when you run the build task. https://hexdocs.pm/elasticsearch/Mix.Tasks.Elasticsearch.Build.html#content
