### ISSUE TITLE
Release 1.0.1

### ISSUE THREAD

**Issue by soundmonster** [danielberkompas/elasticsearch-elixir#91]
The last version released to Hex has been 1.0.0 from March 2019. [Five PRs](https://github.com/danielberkompas/elasticsearch-elixir/pulls?q=is%3Apr+is%3Aclosed+updated%3A%3E2019-04-01+) have been merged since; would it make sense to release these fixes to Hex?

**Comment by danielberkompas** [comment]
I just released 1.0.1. https://hexdocs.pm/elasticsearch/1.0.1/readme.html

**Comment by soundmonster** [comment]
Thank you very much!
